theme: jekyll-theme-tactile
title: [The cool patent]
description: [Finding the common characteristics or relations to their features among influential patents can help inventors to follow the same practice. And moreover it opens possibility of predicting patent’s influentience.]
